minimumReleaseAge: 1440
overrides:
  lodash@<=4.17.23: '>=4.18.0'
  lodash@>=4.0.0 <=4.17.23: '>=4.18.0'
shellEmulator: true
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - "semver@6.3.1" # временно до обновления @rollup/plugin-babel, gh-pages и удаления eslint-config-standard
