minimumReleaseAge: 1440
strictDepBuilds: true
trustPolicy: no-downgrade
shellEmulator: true
trustPolicyExclude:
 - "semver@6.3.1" # FIX: временно eslint-config-standard + @rollup/plugin-babel +  gh-pages
blockExoticSubdeps: true
verifyStoreIntegrity: true
